# Generated by Django 6.0.1 on 2026-01-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuetype',
            name='description',
        ),
        migrations.AddField(
            model_name='issuetype',
            name='sample_form',
            field=models.TextField(blank=True, null=True),
        ),
    ]
